# Generated by Django 4.2.11 on 2026-04-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_google_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_active_artifact_state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_active_chat_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
